// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/12/2026, 11:39:17 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/rahmatjon974/Desktop/WebUsta/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rahmatjon974/Desktop/WebUsta/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rahmatjon974/Desktop/WebUsta/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rahmatjon974/Desktop/WebUsta/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rahmatjon974/Desktop/WebUsta/plugins/**/*.{js,ts,mjs}","/Users/rahmatjon974/Desktop/WebUsta/composables/**/*.{js,ts,mjs}","/Users/rahmatjon974/Desktop/WebUsta/utils/**/*.{js,ts,mjs}","/Users/rahmatjon974/Desktop/WebUsta/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rahmatjon974/Desktop/WebUsta/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/rahmatjon974/Desktop/WebUsta/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/rahmatjon974/Desktop/WebUsta/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;