// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/25/2026, 9:24:38 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/rahmatjon/Downloads/webusta/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rahmatjon/Downloads/webusta/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rahmatjon/Downloads/webusta/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rahmatjon/Downloads/webusta/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rahmatjon/Downloads/webusta/plugins/**/*.{js,ts,mjs}","/Users/rahmatjon/Downloads/webusta/composables/**/*.{js,ts,mjs}","/Users/rahmatjon/Downloads/webusta/utils/**/*.{js,ts,mjs}","/Users/rahmatjon/Downloads/webusta/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rahmatjon/Downloads/webusta/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/rahmatjon/Downloads/webusta/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/rahmatjon/Downloads/webusta/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;